import type { MetadataRoute } from "next";

// Web app manifest — lets Upper install cleanly to a phone home
// screen as a standalone app. The PNG icons are generated by
// scripts/gen-icon.mjs; iOS uses src/app/apple-icon.png instead.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Upper",
    short_name: "Upper",
    description: "Short, social games for the group.",
    start_url: "/",
    display: "standalone",
    background_color: "#f4ede0",
    theme_color: "#d6471f",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
  };
}
