// Generates Upper's app icon set. Run: `node scripts/gen-icon.mjs`.
//
// A white up-arrow on a conic colour sweep through the four palette
// accents (parchment red, noir coral, bloom magenta, marine blue).
// SVG has no native conic gradient, so the sweep is built from many
// thin interpolated wedges — crisp at every size, favicon included.
//
// Outputs:
//   src/app/icon.svg        rounded — the favicon / browser-tab icon
//   src/app/apple-icon.png  180² square — iOS home-screen icon
//   public/icon-192.png     192² square — web manifest
//   public/icon-512.png     512² square — web manifest
//
// The PNGs are square + full-bleed (no rounded corners): iOS and
// Android launchers apply their own mask, so the artwork must reach
// the edges. Rasterised with macOS `qlmanage`.
import { execSync } from "node:child_process";
import { mkdtempSync, writeFileSync, copyFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// The four palette hero accents, with the angle (degrees, clockwise
// from the top) each sits at in colour space.
const STOPS = [
  { deg: 0, rgb: [214, 71, 31] }, // parchment red  #d6471f
  { deg: 110, rgb: [255, 107, 74] }, // noir coral     #ff6b4a
  { deg: 220, rgb: [224, 32, 122] }, // bloom magenta  #e0207a
  { deg: 320, rgb: [47, 92, 255] }, // marine blue    #2f5cff
  { deg: 360, rgb: [214, 71, 31] }, // back to red
];

const WEDGES = 90; // 4° each — smooth at any rendered size
const CENTER = 32;
const RADIUS = 48; // covers the 64×64 square's corners
// Rotate the whole sweep so the lone warm→cool (blue→red) blend lands
// at the bottom, tucked behind the arrow's stem, not at the top edge.
const ROTATE = 200;

const lerp = (a, b, t) => Math.round(a + (b - a) * t);

function colorAt(deg) {
  for (let i = 0; i < STOPS.length - 1; i++) {
    const lo = STOPS[i];
    const hi = STOPS[i + 1];
    if (deg >= lo.deg && deg <= hi.deg) {
      const t = (deg - lo.deg) / (hi.deg - lo.deg);
      const [r, g, b] = [0, 1, 2].map((c) => lerp(lo.rgb[c], hi.rgb[c], t));
      return `rgb(${r},${g},${b})`;
    }
  }
  return "rgb(214,71,31)";
}

// Point on the sweep circle for an angle measured clockwise from top.
function point(deg) {
  const rad = (deg * Math.PI) / 180;
  const x = CENTER + RADIUS * Math.sin(rad);
  const y = CENTER - RADIUS * Math.cos(rad);
  return `${x.toFixed(2)} ${y.toFixed(2)}`;
}

// Chunky up-arrow — the same silhouette Upper has always used.
const ARROW = "M32 11 L55 34 L42 34 L42 55 L22 55 L22 34 L9 34 Z";

function buildSvg(rounded) {
  const wedges = [];
  for (let i = 0; i < WEDGES; i++) {
    const a1 = (i / WEDGES) * 360;
    const a2 = ((i + 1) / WEDGES) * 360;
    const fill = colorAt(((a1 + a2) / 2 - ROTATE + 360) % 360);
    // Stroke each wedge in its own colour so neighbours overlap by a
    // hair — without it, anti-aliasing leaves faint radial seams.
    wedges.push(
      `    <path d="M${CENTER} ${CENTER} L${point(a1)} L${point(a2)} Z" fill="${fill}" stroke="${fill}" stroke-width="1" stroke-linejoin="round"/>`
    );
  }
  const ground = rounded
    ? `  <clipPath id="round">\n    <rect width="64" height="64" rx="14"/>\n  </clipPath>\n  <g clip-path="url(#round)">\n${wedges.join("\n")}\n  </g>`
    : `  <g>\n${wedges.join("\n")}\n  </g>`;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Upper — a white up-arrow on a conic sweep through the four palette
     accents. Generated by scripts/gen-icon.mjs; edit there, not here. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
${ground}
  <path d="${ARROW}" fill="#FFFDF8"/>
</svg>
`;
}

const root = new URL("..", import.meta.url);
const at = (p) => new URL(p, root).pathname;

// 1. The rounded favicon SVG.
writeFileSync(at("src/app/icon.svg"), buildSvg(true));

// 2. Rasterise the square, full-bleed variant into the PNG sizes.
const work = mkdtempSync(join(tmpdir(), "upper-icon-"));
const squareSvg = join(work, "icon-square.svg");
writeFileSync(squareSvg, buildSvg(false));

const pngs = [
  { out: "src/app/apple-icon.png", size: 180 },
  { out: "public/icon-192.png", size: 192 },
  { out: "public/icon-512.png", size: 512 },
];
for (const { out, size } of pngs) {
  execSync(
    `qlmanage -t -s ${size} -o ${work} ${squareSvg}`,
    { stdio: "ignore" }
  );
  copyFileSync(join(work, "icon-square.svg.png"), at(out));
}

console.log(
  `Wrote src/app/icon.svg + ${pngs.map((p) => p.out).join(", ")}`
);
